set -g default-shell /usr/bin/nu

# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

# move starting index for panes/windows
set -g base-index 1
setw -g pane-base-index 1

# set escape delay
set -sg escape-time 0

# set splitting commands (always use prefix before)
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# set true color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# allow passthrough from commands to the external terminal
set -g allow-passthrough on
